encoding: UTF-8
title: "cas.eliens.co"
future: false
theme: jekyll-theme-midnight
gfm_quirks: paragraph_end
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Cas Eliëns"
            layout: "post"
