encoding: UTF-8
kramdown:
    input: GFM
    hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-hacker
gfm_quirks: paragraph_end
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            author: "Cas Eliëns"
